apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ include "domain.fullname" . }}-pull-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
