apiVersion: v1
kind: Secret
metadata:
  name: {{ include "domain.fullname" . }}-weblogic-credentials
data:
  username: {{ .Values.weblogic.username  | b64enc }}
  password: {{ .Values.weblogic.password  | b64enc }}
